# Generated by Django 3.1.6 on 2021-11-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.CharField(blank=True, default='OD20210611/24/21130640', max_length=50),
        ),
    ]
