# Generated by Django 3.1.6 on 2021-11-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.CharField(blank=True, default='OD202108130850', max_length=50),
        ),
    ]
